// <auto-generated />

using CurrencyHandler.Models.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyHandler.Migrations
{
    [DbContext(typeof(ChatSettingsContext))]
    partial class ChatSettingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CurrencyHandler.Models.ChatSettingsDB.ChatSettings", b =>
                {
                    b.Property<int>("ChatSettingsId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ChatId");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("UAH");

                    b.Property<decimal>("Percents")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(100m);

                    b.HasKey("ChatSettingsId");

                    b.ToTable("ChatSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
